services:
    clickhouse:
        image: clickhouse/clickhouse-server:latest
        container_name: benchmark-clickhouse
        environment:
            - CLICKHOUSE_USER=default
            - CLICKHOUSE_PASSWORD=clickhouse_password
            - CLICKHOUSE_DB=benchmark_db
        ports:
            - "8123:8123"
            - "9000:9000"
        volumes:
            - chdata:/var/lib/clickhouse

volumes:
    chdata:
