services:
    clickhouse:
        image: clickhouse/clickhouse-server:latest
        container_name: clickhouse
        restart: unless-stopped
        environment:
            CLICKHOUSE_USER: ${CLICKHOUSE_USER}
            CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
            CLICKHOUSE_DB: ${CLICKHOUSE_DB}
        ports:
            - "${CLICKHOUSE_PORT:-8123}:8123"
            - "9000:9000"
        volumes:
            - chdata:/var/lib/clickhouse

volumes:
    chdata:
