[project]
name = "postgres-vs-clickhouse"
version = "0.1.0"
description = "postgres-vs-clickhouse"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clickhouse-connect>=1.4.1",
    "fastapi>=0.139.0",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.50.1",
]

[dependency-groups]
dev = [
    "ruff>=0.15.21",
]
