"""create_initial_tables

Revision ID: 6f120aaa74e3
Revises: 
Create Date: 2026-07-13 08:35:50.257114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f120aaa74e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_tokens', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'api_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_tokens', type_='foreignkey')
    op.drop_column('api_tokens', 'user_id')
    # ### end Alembic commands ###
